apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jhgq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-isyf-tenant/rhtap-demo-app/hacbs-test-project-jhgq@sha256:0bc3ec7ce04f0af324424d9c7d585a8ff00b2ebe228d09577cec4329ccff4ba8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
