apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jhgq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jhgq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jhgq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jhgq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jhgq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-isyf-tenant/rhtap-demo-app/hacbs-test-project-jhgq@sha256:50f3b7c3a8de904f03c0053362ade35d3085da12751fdf1afd5f3cf0a69c79e4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
